services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rusty-chat
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
